swagger: '2.0'

info:
  title: 'Generative Recipes Microservice'
  version: '1.0'
  description: "This is a minimal REST API microservice to serve generative AI images for a prompt.\nThe base-path of the API is `/v1`"
  contact:
    name: Albert Ferguson
  license:
    name: MIT
    url: https://github.com/albert118/GenerativeRecipes/blob/master/LICENSE

basePath: /v1

schemes:
  - https
# securityDefinitions:
#   basicAuth:
#     type: basic
#     x-basicInfoFunc: api.accounts.basic_auth

paths:
  /images/generate-image?prompt={prompt}:
    get:
      tags:
        - public
      operationId: api.images.generate_image
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: prompt
          type: string
          required: true
          description: Prompt to generate an image
      responses:
        202:
          description: Successfully queued job
        400:
          description: Invalid prompt (no job was queued)
        429:
          description: Too many requests (rate limited)

tags:
  - name: public
    description: Operations available for (authorised) public consumption
  - name: admins
    description: Secured admin-only calls

definitions:
  User:
    type: object
    properties:
      id: { type: string }
      username: { type: string }
      password: { type: string }
